// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://hacsmddazijrghfcoigl.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhY3NtZGRhemlqcmdoZmNvaWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDU5OTQsImV4cCI6MjA3MzI4MTk5NH0.TvVm0dUGVE32gEBdcoNLD3qo78BxgQy8DFJUpubdn9M";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});