// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seqtrhqewkaelsbowmrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlcXRyaHFld2thZWxzYm93bXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDQyNDgsImV4cCI6MjA3MzI4MDI0OH0.VYpVbnbRF9AYPdf3BYILEsV1Xnsc4-tsVULyUAgrCDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});